/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game_of_life;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import game_of_life.models.Cell;
import game_of_life.network.Client;
import game_of_life.network.Server;
import game_of_life.utils.Constants;
import game_of_life.views.AppView;
import javafx.animation.AnimationTimer;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

public class App extends Application {

    private ArrayList<ArrayList<Cell>> cells = new ArrayList<ArrayList<Cell>>();
    private AppView controller;
    private Server server;

    @Override
    public void start(Stage primaryStage) throws Exception {
        controller = new AppView();
        initCells();
        AnimationTimer timer = new AnimationTimer() {
            private long lastUpdate = 0;

            @Override
            public void handle(long now) {
                if (now - lastUpdate >= Constants.TIMEOUT) {
                    if (server != null && server.getClientCount() > 0) {
                        try {
                            controller.setClientsLbl(server.getClientCount());
                            cells = server.calculate(cells);
                            controller.display(cells);
                        } catch (Exception e) {
                            // TODO Auto-generated catch block
                            e.printStackTrace();
                        }
                    }
                    lastUpdate = now;
                }

            }
        };
        controller.startBtn.setOnAction((event) -> {
            timer.start();
            controller.addClientBtn.setDisable(false);
            controller.stopBtn.setDisable(false);
            controller.startBtn.setDisable(true);
        });
        controller.stopBtn.setOnAction((event) -> {
            timer.stop();
            controller.stopBtn.setDisable(true);
            controller.startBtn.setDisable(false);
        });
        controller.restartBtn.setOnAction((event) -> {
            timer.stop();
            cells = new ArrayList<ArrayList<Cell>>();
            initCells();
            controller.stopBtn.setDisable(false);
            controller.startBtn.setDisable(true);
            timer.start();
        });
        controller.addClientBtn.setOnAction((event) -> {
            new Thread(new Client()).start();
        });

        // Network
        server = new Server();
        new Thread(server).start();
        List<Thread> clients = new ArrayList<Thread>();
        final int noClients = 2;
        for (int i = 0; i < noClients; i++) {
            Thread t = new Thread(new Client());
            t.setName("client socket thread: " + (i));
            clients.add(t);
        }
        clients.forEach(c -> c.start());
        controller.setClientsLbl(clients.size());
        // Clean up resources on exit
        primaryStage.setOnCloseRequest(new EventHandler<WindowEvent>() {
            @Override
            public void handle(WindowEvent t) {
                cells = null;
                Platform.exit();
                System.exit(0);
            }
        });
        primaryStage.setTitle("Grid");
        primaryStage.setScene(new Scene(controller));
        // primaryStage.setResizable(false);
        primaryStage.show();
    }

    /**
     * Initialize the two dimensional Cell array
     */
    private void initCells() {
        Random rand = new Random();
        for (int i = 0; i < Constants.COLS; i++) {
            ArrayList<Cell> newCells = new ArrayList<>();
            for (int j = 0; j < Constants.ROWS; j++) {
                newCells.add(new Cell(rand.nextInt(2)));
            }
            cells.add(newCells);
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}
