/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game_of_life;

import org.junit.Test;

import game_of_life.models.Cell;
import game_of_life.utils.GameOfLife;

import java.util.ArrayList;

import static org.junit.Assert.assertArrayEquals;

public class GameOfLifeTest {
  @Test
  public void testBlockPattern() {
    int cols = 4;
    int rows = 4;
    GameOfLife gol = new GameOfLife(cols, rows);
    ArrayList<ArrayList<Cell>> expected_cells = new ArrayList<ArrayList<Cell>>();
    // Init the expected_cells array with alive cells at: [1,1],[1,2],[2,1],[2,2]
    for (int i = 0; i < cols; i++) {
      ArrayList<Cell> _temp = new ArrayList<>();
      for (int j = 0; j < rows; j++) {
        if ((i == 1 && j == 1) || (i == 1 && j == 2) || (i == 2 && j == 1) || (i == 2 && j == 2)) {
          _temp.add(new Cell(1));
        } else {
          _temp.add(new Cell(0));
        }
      }
      expected_cells.add(_temp);
    }
    // Compute next generation
    ArrayList<ArrayList<Cell>> cells = gol.compute(expected_cells);

    // Compare
    assertArrayEquals(expected_cells.toArray(), cells.toArray());
  }

  @Test
  public void testTubPattern() {
    int cols = 5;
    int rows = 5;
    GameOfLife gol = new GameOfLife(cols, rows);
    ArrayList<ArrayList<Cell>> expected_cells = new ArrayList<ArrayList<Cell>>();
    // Init the expected_cells array with alive cells at: [1,1],[1,2],[2,1],[2,2]
    for (int i = 0; i < cols; i++) {
      ArrayList<Cell> _temp = new ArrayList<>();
      for (int j = 0; j < rows; j++) {
        if ((i == 1 && j == 2) || (i == 2 && j == 1) || (i == 2 && j == 3) || (i == 3 && j == 2)) {
          _temp.add(new Cell(1));
        } else {
          _temp.add(new Cell(0));
        }
      }
      expected_cells.add(_temp);
    }
    // Compute next generation
    ArrayList<ArrayList<Cell>> cells = gol.compute(expected_cells);
    // Compare
    assertArrayEquals(expected_cells.toArray(), cells.toArray());
  }

  @Test
  public void testBlinkerPattern() {

  }

  @Test
  public void testGliderPattern() {

  }

}
